tajisoft/droneschool

dronekit_scripts/011_connect.py, dronekit_scripts/012_attribute.py, dronekit_scripts/013_attribute_util.py, dronekit_scripts/014_takeoff.py, dronekit_scripts/015_takeoff_util.py
Day1のサンプルコードを追加しました。
同じ内容のソースコードがあるようですが、触っていません。
カリキュラムの順番に並ぶよう数字プレフィックスをつけています。問題あればお知らせください。
=> add Day1 sample codes

dronekit_scripts/201_listener.py, dronekit_scripts/202_decorator.py, dronekit_scripts/203_parameter.py, dronekit_scripts/204_parameter_listener.py, dronekit_scripts/205_parameter_decorator.py, dronekit_scripts/206_home_location.py, dronekit_scripts/207_simplegoto.py, dronekit_scripts/208_attitude.py, dronekit_scripts/209_position.py, dronekit_scripts/210_command.py, dronekit_scripts/211_mission_basic.py, dronekit_scripts/212_mission_create.py, dronekit_scripts/213_mission_modify.py, dronekit_scripts/214_mission_next.py, dronekit_scripts/215_mavlink_decorator.py, dronekit_scripts/216_mavlink_listener.py, dronekit_scripts/217_distance_sensor.py
（Dronekit-Pythonの）Day2のサンプルコードを追加しました。
=> add Day2 samples

pymavlink_scripts/01_message_dump.py, pymavlink_scripts/02_arm_disarm.py, pymavlink_scripts/03_change_mode.py, pymavlink_scripts/04_read_params.py
接続文字列をTCPに統一、モード変更スクリプトのバグ修正をしました。
=> update connection strings, fix bug of mode change

doc/ArduPilot-dev-docker.md
WindowsのDocker環境セットアップ手順を追加しました。他も微修正しています。
確認お願いいたします。
=> Doc: add docker setup for Windows

pymavlink_scripts/pm01_message_dump.py, pymavlink_scripts/pm50_mission_basics.py
=> fix sourcecode errors in the 16th-day2 class

workshop/17th/hiroaki-kawasaki/README.md
=> Modified for the workshop

pymavlink_scripts/pm01_message_basics.py, pymavlink_scripts/pm01_message_dump.py, pymavlink_scripts/pm02_arm_disarm.py, pymavlink_scripts/pm04_change_mode_prompt.py, pymavlink_scripts/pm40_location_control.py
=> bugfix in pymavlink samples

workshop/17th/ryoichi-shiohama/README.md
=> 17期 workshop用にREADME.mdを追加しました

pymavlink_scripts/pm01_message_dump.py, workshop/17th/yoshikazu-KURAMOTO/README.md
=> 17th yoshikazu kuramoto

workshop/17th/kei-kabutomori/README.md
=> Add 17th workshop folder with README.md

workshop/17th/kei-kabutomori/README.md, workshop/17th/kei-kabutomori/dronekit_ver_test014_takeoff-check.py, workshop/17th/kei-kabutomori/dronekit_ver_test208_attitude-ctrl.py, workshop/17th/kei-kabutomori/pymavlink_ver_test10_takeoff-check.py, workshop/17th/kei-kabutomori/pymavlink_ver_test41_attitude-ctrl.py
17期DAY3宿題対応の第一弾として2024/06/30まで実行した内容をUP(兜森)
=> Add 17th workshop folder with Homework part1 k-kabuto

workshop/17th/kei-kabutomori/dronekit_ver_test213.py
Homework I forgot to address on Drone School Day3
=> Add Day3 HomeWork

workshop/17th/ryoga-kamimura/README.md, workshop/17th/ryoga-kamimura/move_by_input_meter.py, workshop/17th/ryoga-kamimura/pm40_location_control.py
- pm40_location_control.pyを写経
- move_by_input_meter.pyを作成
- README.mdをアップデート
=> 宿題の写経と終了課題を追加しました。

workshop/17th/ryoichi-shiohama/README.md, workshop/17th/ryoichi-shiohama/pymavlink_scripts/day3_homework_original_app/mission_utils.py, workshop/17th/ryoichi-shiohama/pymavlink_scripts/day3_homework_original_app/original_mission.py
[Day3宿題で作りきれなかった](https://github.com/tajisoft/droneschool/pull/24)、自動航行が動作するようにした差分PRです。
「アーム > 離陸 > 自動航行（三角軌道） > RTL」の処理を作成しました。
=> [終了課題] 自動航行オリジナルアプリ作成

workshop/18th/haruki-mukai/Readme.md
* 第18期ワークショップ用フォルダーを作成
* 当該フォルダ内にReadme.mdを作成、Hello入力
=> 第18期ワークショップフォルダーとReadmeを追加

workshop/18th/aoi-yoshino/README.md
this is my first pull request.
=> Add 18th workshop folder with README.md

workshop/18th/naoya-hirota/README.md, workshop/18th/naoya-hirota/pm00_connect_heartbeat.py, workshop/18th/naoya-hirota/pm10_takeoff.py, workshop/18th/naoya-hirota/pm30_home_location.py
create 18th workshop folder and homework
=> add 18th workshop with homework

workshop/18th/haruki-mukai/auto_flight_SOS.py
FlightExperience用のスクリプトです。
GPSの現在地を西北、左上の基準点として南東方向にSOSの文字を斜めに描画します。
arm→10mホバリング→GPSの詳細座標取得→GPSの現在地を元にフライトプランを作成→フライトプランに従って飛行→RTL
SITLでは飛行確認済みです。
(一応、飛行スケールを指定できるようにしておきました)
=> add Script for 18th Flight Experience

workshop/18th/naoto-ueno/pm_experience_ueno.py, workshop/18th/naoto-ueno/utils.py
Day 4のためのプログラムを作成しました。
プログラムの趣旨は、
アームした位置を原点とし、複数の点の相対位置を与えると、
その点を中心に一回りするものです。
これは、森林内の樹木の周囲を飛行し画像や点群データを取得することを想定しています。
よろしくお願いします。
=> 18th naoto ueno

workshop/18th/naoto-ueno/homework/conn.py, workshop/18th/naoto-ueno/homework/exam_program.py, workshop/18th/naoto-ueno/homework/pm10_takeoff_copy.py, workshop/18th/naoto-ueno/homework/pm40_location_control_copy.py, workshop/18th/naoto-ueno/homework/pm43_command_copy.py, workshop/18th/naoto-ueno/homework/utils.py
Day3 宿題3の写経3本の課題です。
pm10_takeoff_copy.py
pm40_location_control_copy.py
pm43_command_copy.py
それぞれ、_copyを取ったものがオリジナルです。
=> 18th school day 4 homework (Naoto Ueno)

workshop/18th/yuka-inaba/day4.py
FlightExperience用に作成したスクリプトです．
まだ準備途中なのですが，ドローンに搭載したロボットアームの先に力覚センサを取り付け，降下途中にアーム先端が地面に接触したら，上昇を始めるような実験を行う予定です．
ー現時点でのコードフローー
高度2mまで離陸→0.7m前進→0.1m/sで10秒間降下（力覚センサから信号を受け取ったら，降下をやめるように変更予定）→高度2mまで上昇→0.7m後進→着陸
SITLでは飛行確認済みです．
=> add Script 18th

workshop/19th/TETSUO-TODA/README.md, workshop/19th/tetsuo_toda/README.md
=> Add 19th workshop folder with README.md

pymavlink_scripts/pm00_connect_heartbeat.py, workshop/19th/yusuke-ota/README.md, workshop/19th/yusuke-ota/flight_experience_ota.py, workshop/19th/yusuke-ota/my_drone_pkg/CMakeLists.txt, workshop/19th/yusuke-ota/my_drone_pkg/package.xml, workshop/19th/yusuke-ota/my_drone_pkg/scripts/generate_figure_eight_client.py, workshop/19th/yusuke-ota/my_drone_pkg/services/arm_disarm_service.py, workshop/19th/yusuke-ota/my_drone_pkg/services/mission_upload_server.py, workshop/19th/yusuke-ota/my_drone_pkg/services/set_mode_service.py, workshop/19th/yusuke-ota/my_drone_pkg/services/takeoff_service.py, workshop/19th/yusuke-ota/my_drone_pkg/srv/SetArm.srv, workshop/19th/yusuke-ota/my_drone_pkg/srv/SetMode.srv, workshop/19th/yusuke-ota/my_drone_pkg/srv/SetTakeoff.srv, workshop/19th/yusuke-ota/my_drone_pkg/srv/UploadMission.srv, workshop/19th/yusuke-ota/my_drone_pkg/tests/test_arm_disarm_service.py, workshop/19th/yusuke-ota/my_drone_pkg/tests/test_nav_waypoint.py, workshop/19th/yusuke-ota/my_drone_pkg/tests/test_set_mode_service.py, workshop/19th/yusuke-ota/my_drone_pkg/tests/test_takeoff_service.py
コメントアウトの修正
地面でアームし、南東に5m進んだ後、機首固定の8の字飛行をし、RTLで帰還するプログラム
mavrosもどきをつくってインタラクティブに動かそうかと思ったのですが、断念。
arm/disarm, mode変更, takeoffまでできます。
=> 0628_flightexperience
